server:
    port: 9090
    context-path: #/jason/

logging:
    level:
        business.mybatis: TRACE

spring:
    datasource:
        name: bszb
        url: jdbc:mysql://120.26.120.234:3306/bszb
        username: bszb
        password: bszbBase2016

    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: business.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - business.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql